### ISSUE TITLE
Missing examples for other cloud variants

### ISSUE THREAD

**Issue by luisdavim** [gardener/landscape-setup-template#6]
The the landscape.yaml mentions other variants but the configuration seems specific to AWS, can you add examples for the other supported cloud providers?

**Comment by marwinski** [comment]
We are currently working on extending the installer to OpenStack environments. As for Azure and GCP this will probably take some more time on our side but the necessary files and documentation are part of the gardener (cloud profile, seed configuration) and kubify projects. What cloud variant are you looking for?

**Comment by luisdavim** [comment]
Hi, Thanks for your reply. 
I'm actually interested in the azure variant. And I've also noticed that your "bring your own cluster" is missing some steps, like setting up certs and stuff like that.

**Comment by vlerenc** [comment]
Just in case, that's an option: The Gardener itself provides clusters on all four infrastructures. Where it is installed or where the seed cluster runs is (almost) irrelevant (you do not need this landscape-setup, but it makes its deployment easier). Of course, being in the same region on the same infrastructure has performance/latency advantages.

Anyway, just saying. We have tried setups where we host the Gardener on OpenStack, have a seed in GCP, run shoots on Azure, AWS and again GCP. That is all working.

However, the landscape-setup that makes general consumption easier, as Dirk pointed out, is not available for all infrastructures.

**Comment by bergerx** [comment]
Maybe having the implementation state with the different cloud provides documented somewhere could help others that want to try gardener. We've been thinking about trying Gardener on Azure but it's not easy to figure out it's state with Azure. Having AWS account documented as a prerequisite in https://github.com/gardener/landscape-setup-template#prerequisites gives some clue about its AWS only for now but not clear.

**Comment by bergerx** [comment]
:) I take my last comment back, because just saw this in the readme already, its actually quite clear:
> Gardener currently supports AWS, Azure, GCP, and OpenStack but this project only contains configurations and scripts for AWS. We are looking for help to extend the installation procedure to other cloud providers.

**Comment by Diaphteiros** [comment]
This project has been expanded to support Openstack as well by now.

**Comment by msohn** [comment]
Could you then please update
https://github.com/gardener/landscape-setup-template/blob/master/README.md
accordingly ?

**Comment by Diaphteiros** [comment]
The readme has been improved/fixed to show the supported cloud providers at the beginning instead of only somewhere in the last paragraph. Currently on dev branch: https://github.com/gardener/landscape-setup-template/blob/dev/README.md
